# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import api.protoc.Advertise_pb2 as Advertise__pb2


class ADServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AdPosition = channel.unary_unary(
        '/admin.ADService/AdPosition',
        request_serializer=Advertise__pb2.AdPositionRequest.SerializeToString,
        response_deserializer=Advertise__pb2.AdPositionResponse.FromString,
        )


class ADServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AdPosition(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ADServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AdPosition': grpc.unary_unary_rpc_method_handler(
          servicer.AdPosition,
          request_deserializer=Advertise__pb2.AdPositionRequest.FromString,
          response_serializer=Advertise__pb2.AdPositionResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'admin.ADService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
