# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Index.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import src.api.protoc.Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Index.proto',
  package='admin',
  syntax='proto3',
  serialized_options=_b('\n\033com.talkweb.admins.protobufB\005Index\242\002\002SN'),
  serialized_pb=_b('\n\x0bIndex.proto\x12\x05\x61\x64min\x1a\x0c\x43ommon.proto\"4\n\x0cIndexRequest\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.admin.HeaderMessage\"7\n\rIndexResponse\x12&\n\x07reqCode\x18\x01 \x01(\x0b\x32\x15.admin.ReqCodeMessage2\xf7\x01\n\x0cIndexService\x12\x32\n\x05index\x12\x13.admin.IndexRequest\x1a\x14.admin.IndexResponse\x12;\n\x0cserverStream\x12\x13.admin.IndexRequest\x1a\x14.admin.IndexResponse0\x01\x12;\n\x0c\x63lientStream\x12\x13.admin.IndexRequest\x1a\x14.admin.IndexResponse(\x01\x12\x39\n\x08\x62\x64Stream\x12\x13.admin.IndexRequest\x1a\x14.admin.IndexResponse(\x01\x30\x01\x42)\n\x1b\x63om.talkweb.admins.protobufB\x05Index\xa2\x02\x02SNb\x06proto3')
  ,
  dependencies=[Common__pb2.DESCRIPTOR,])




_INDEXREQUEST = _descriptor.Descriptor(
  name='IndexRequest',
  full_name='admin.IndexRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='admin.IndexRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=88,
)


_INDEXRESPONSE = _descriptor.Descriptor(
  name='IndexResponse',
  full_name='admin.IndexResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reqCode', full_name='admin.IndexResponse.reqCode', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=145,
)

_INDEXREQUEST.fields_by_name['header'].message_type = Common__pb2._HEADERMESSAGE
_INDEXRESPONSE.fields_by_name['reqCode'].message_type = Common__pb2._REQCODEMESSAGE
DESCRIPTOR.message_types_by_name['IndexRequest'] = _INDEXREQUEST
DESCRIPTOR.message_types_by_name['IndexResponse'] = _INDEXRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IndexRequest = _reflection.GeneratedProtocolMessageType('IndexRequest', (_message.Message,), {
  'DESCRIPTOR' : _INDEXREQUEST,
  '__module__' : 'Index_pb2'
  # @@protoc_insertion_point(class_scope:admin.IndexRequest)
  })
_sym_db.RegisterMessage(IndexRequest)

IndexResponse = _reflection.GeneratedProtocolMessageType('IndexResponse', (_message.Message,), {
  'DESCRIPTOR' : _INDEXRESPONSE,
  '__module__' : 'Index_pb2'
  # @@protoc_insertion_point(class_scope:admin.IndexResponse)
  })
_sym_db.RegisterMessage(IndexResponse)


DESCRIPTOR._options = None

_INDEXSERVICE = _descriptor.ServiceDescriptor(
  name='IndexService',
  full_name='admin.IndexService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=148,
  serialized_end=395,
  methods=[
  _descriptor.MethodDescriptor(
    name='index',
    full_name='admin.IndexService.index',
    index=0,
    containing_service=None,
    input_type=_INDEXREQUEST,
    output_type=_INDEXRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='serverStream',
    full_name='admin.IndexService.serverStream',
    index=1,
    containing_service=None,
    input_type=_INDEXREQUEST,
    output_type=_INDEXRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='clientStream',
    full_name='admin.IndexService.clientStream',
    index=2,
    containing_service=None,
    input_type=_INDEXREQUEST,
    output_type=_INDEXRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='bdStream',
    full_name='admin.IndexService.bdStream',
    index=3,
    containing_service=None,
    input_type=_INDEXREQUEST,
    output_type=_INDEXRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_INDEXSERVICE)

DESCRIPTOR.services_by_name['IndexService'] = _INDEXSERVICE

# @@protoc_insertion_point(module_scope)
