# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import src.api.protoc.Index_pb2 as Index__pb2


class IndexServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.index = channel.unary_unary(
        '/admin.IndexService/index',
        request_serializer=Index__pb2.IndexRequest.SerializeToString,
        response_deserializer=Index__pb2.IndexResponse.FromString,
        )
    self.serverStream = channel.unary_stream(
        '/admin.IndexService/serverStream',
        request_serializer=Index__pb2.IndexRequest.SerializeToString,
        response_deserializer=Index__pb2.IndexResponse.FromString,
        )
    self.clientStream = channel.stream_unary(
        '/admin.IndexService/clientStream',
        request_serializer=Index__pb2.IndexRequest.SerializeToString,
        response_deserializer=Index__pb2.IndexResponse.FromString,
        )
    self.bdStream = channel.stream_stream(
        '/admin.IndexService/bdStream',
        request_serializer=Index__pb2.IndexRequest.SerializeToString,
        response_deserializer=Index__pb2.IndexResponse.FromString,
        )


class IndexServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def index(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def serverStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def clientStream(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def bdStream(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IndexServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'index': grpc.unary_unary_rpc_method_handler(
          servicer.index,
          request_deserializer=Index__pb2.IndexRequest.FromString,
          response_serializer=Index__pb2.IndexResponse.SerializeToString,
      ),
      'serverStream': grpc.unary_stream_rpc_method_handler(
          servicer.serverStream,
          request_deserializer=Index__pb2.IndexRequest.FromString,
          response_serializer=Index__pb2.IndexResponse.SerializeToString,
      ),
      'clientStream': grpc.stream_unary_rpc_method_handler(
          servicer.clientStream,
          request_deserializer=Index__pb2.IndexRequest.FromString,
          response_serializer=Index__pb2.IndexResponse.SerializeToString,
      ),
      'bdStream': grpc.stream_stream_rpc_method_handler(
          servicer.bdStream,
          request_deserializer=Index__pb2.IndexRequest.FromString,
          response_serializer=Index__pb2.IndexResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'admin.IndexService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
